export const EXAMPLE_REDIS_CONFIG = Symbol('EXAMPLE_REDIS_CONFIG');
export const EXAMPLE_REDIS_CONNECTION = Symbol('EXAMPLE_REDIS_CONNECTION');
export const EXAMPLE_WORKFLOW_QUEUE = Symbol('EXAMPLE_WORKFLOW_QUEUE');
